#!/usr/bin/env ruby

require "Paludis"

require "framework"
require "eric-sync"
require "eric-report"

include Paludis

if ARGV.length == 0
    puts "Usage: ric COMMAND [ARGUMENTS]"
else
    begin
        Log.instance.log_level = LogLevel::Silent
        env = EnvironmentFactory.instance.create(CommandLine.instance.environment)

        case ARGV.first
            when "sync": eric_sync(env, ARGV[1])
            when "report": eric_report(env);
            else puts "No command named '#{ARGV.first}'"
        end
    rescue Exception => e
        puts "An unexpected exception occured: " + e.message
        puts "---------------------"
        puts e.backtrace
    end
end
