#!/usr/bin/env ruby

require "Paludis"

require "framework.rb"
require "ric-sync"

include Paludis

if ARGV.length == 0
    puts "Usage: ric COMMAND [ARGUMENTS]"
else
#    OutputDir = "./output"
    begin
        Log.instance.log_level = LogLevel::Silent
        env = EnvironmentFactory.instance.create(CommandLine.instance.environment)

        arguments = ARGV.pop(ARGV.length - 1)
        case ARGV.first
            when "sync": ric_sync(env)
            else puts "No command named '#{ARGV.first}'"
        end
    rescue
        puts "Something unexpected happened"
    end
end
