#!/usr/bin/env ruby

require "Paludis"

require "framework"
require "ric-sync"
require "ric-report"

include Paludis

if ARGV.length == 0
    puts "Usage: ric COMMAND [ARGUMENTS]"
else
#    OutputDir = "./output"
    begin
        Log.instance.log_level = LogLevel::Silent
        env = EnvironmentFactory.instance.create(CommandLine.instance.environment)

        arguments = ARGV.pop(ARGV.length - 1)
        case ARGV.first
            when "sync": ric_sync(env)
            when "report": ric_report;
            else puts "No command named '#{ARGV.first}'"
        end
    rescue Exception => e
        puts "An unexpected exception occured: " + e.message
    end
end
